config/routes.rb
Rails.application.routes.draw do
  root 'users#show'

  get '/play', to: 'games#play', as: 'game'

  post '/round', to: 'games#round', as: 'round', defaults: { format: :json }
  get '/restart', to: 'games#restart', as: 'restart', defaults: { format: :json }

  devise_for :users, controllers: { registrations: 'registrations' }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user
  before_create :generate_game_public_id

  private

  def generate_game_public_id
    self.public_id = SecureRandom.hex(6) unless self.class.exists?(public_id: public_id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :games, dependent: :destroy
  validates :name, presence: true
  validates :name, length: { minimum: 4 }
  validates :name, uniqueness: true
  devise :database_authenticatable, :registerable, :trackable,
         :recoverable, :rememberable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery unless: -> { request.format.json? }

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :setup_game, only: [:play]
  before_action :check_player_input, only: [:round]
  def play
    session[:game] = { 'round' => 0, 'player_score' => 0, 'computer_score' => 0 }
    @current_game_data = session[:game]
  end

  def round
    round_result = GameRound.new(params[:player_selection], session).play
    session[:game] = round_result[2]
    if round_result[0]
      render json: { "computer_selection": round_result[1], "game_data": session[:game], commentary: round_result[4],
                     "game_status": round_result[3] }
    else
      render json: { error: "can't play more than 5 rounds" }, status: :unprocessable_entity
    end
  end

  def restart
    render json: { info: 'starting new session' }, location: game_path, status: :found
  end

  private

  def setup_game
    @game = current_user.games.create
    game_saved = @game.save
    session[:game_id] = @game.id if game_saved

    redirect_to root_path, alert: 'Unable to launch new game' unless game_saved
  end

  def check_player_input
    unless %w[rock paper scissors].include?(params[:player_selection])
      render json: { error: 'invalid input' }, status: :unprocessable_entity
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def after_inactive_sign_up_path_for(_resource)
    new_user_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user_data = user_data

    @leaders = User.joins(:games).where('games.status': 'win').select('name, count(games.status)').group(:name).order(count: :desc)
                   .limit(10).as_json
  end

  private

  def user_data
    {
      wins: current_user.games.where('status = ?', 'win').count,
      losses: current_user.games.where('status = ?', 'loss').count,
      draws: current_user.games.where('status = ?', 'draw').count,
      games_played: current_user.games.where.not(status: '').count
    }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/play.html.slim
- content_for :head 
  = javascript_import_module_tag 'game'

.go-home
  = link_to 'go home', root_url

.game-container 
  .info 
    .indicator 
    .result-score
      .score
        | Bot 
        span id='computerscore'
          = @current_game_data['computer_score']
        |  - 
        span id='playerscore'
          = @current_game_data['player_score']
        |  You

      . id='result'
        | - -
      .rounds
        | round 
        span id='rounds-text'
          = @current_game_data['round']
        | /5
  .playground 
    . class='area computer'
      .bot-marker
        | Bot
      .buttongroups 
        button data-computerselection='rock'
          = image_tag(image_url('buttons/rock.png'))
        button data-computerselection='paper'
          = image_tag(image_url('buttons/paper.png'))
        button data-computerselection='scissors'
          = image_tag(image_url('buttons/scissors.png'))
    . id='divider'
      | v
    . class='area player'
      .player-marker 
        | You
      .buttongroups 
        button data-playerselection='rock'
          = image_tag(image_url('buttons/rock.png'))
        button data-playerselection='paper'
          = image_tag(image_url('buttons/paper.png'))
        button data-playerselection='scissors'
          = image_tag(image_url('buttons/scissors.png'))

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Rock Paper Scissors
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = favicon_link_tag 'favicon/favicon.ico'
    = favicon_link_tag 'favicon/apple-touch-icon.png', rel: 'apple-touch-icon', type: 'image/png'
    = stylesheet_link_tag "application", 
      "https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap",
      "data-turbo-track": "reload"
    = javascript_importmap_tags
    = yield :head
  body class=controller.controller_name
    .content
      .notice
        = notice
      .alert
        = alert
      = yield
    .sidebar
      .logo 
        .title 
          | RPS 
        .subtitle 
          | Rock Paper Scissors
      = yield :board
      .footer
        | &copy 
        a href='https://chrisadebiyi.com' target='_blank'
          | Chris Oluwafemi Adebiyi 

app/views/users/show.html.slim
- content_for :board 
  .leader-board 
    p Leaderboard 
    table 
      tr 
        th class='head'
          | player 
        th class='head'
          | wins
      - @leaders.each do |leader|
        tr
          td class='entries leader-name'
            = leader['name']
          td class='entries leader-score'
            = leader['count']
.name-and-exit
  .name 
    | @
    = current_user.name
  .signout
      = link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete}
.stats 
  table 
    tr 
      td 
        = @user_data[:games_played]
      td class='stat-labels'
        - if @user_data[:games_played] > 1 || @user_data[:games_played] == 0
          = 'games played'
        - else
          = 'game played'
    tr 
      td 
        = @user_data[:wins] 
      td class='stat-labels'
        - if @user_data[:wins] > 1 || @user_data[:wins] == 0
          = 'wins'
        - else
          = 'win'
    tr 
      td 
        = @user_data[:losses]
      td class='stat-labels'
        - if @user_data[:losses] > 1 || @user_data[:losses] == 0
          = 'losses'
        - else
          = 'loss'
    tr 
      td 
        = @user_data[:draws]
      td class='stat-labels'
        - if @user_data[:draws] > 1 || @user_data[:draws] == 0
          = 'draws'
        - else
          = 'draw'
  . data-turbo="false" class='launch-button'
    = link_to 'Launch New Game', game_url 
  